config/routes.rb
BlogPlanner::Application.routes.draw do

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "home#index"
  devise_for :users
  resource :user, only: ["show"]

  resources :blogs, except: [] do
    resources :planned_dates, except: ["index", "show"]
  end

  #get "faq" => "faq#index"
  get "about" => "about#index"

  #get "/app" => "app#show"
    #namespace :api do
    #resources :blogs
  #end
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :name, :user_id

  belongs_to :user

  has_many :planned_dates
end

app/models/planned_date.rb
class PlannedDate < ActiveRecord::Base
  attr_accessible :blog_id, :content, :date, :title

  belongs_to :blog
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :blogs

  def my_blog?(blog)
    self.blogs.each do |b|
      return true if b.id == blog.id
    end
    false
  end

  def my_planned_date?(date)
    dates = self.blogs.map do |blog|
      blog.planned_dates
    end
    dates.flatten!
    dates.each do |d|
      return true if d.id == date.id
    end
    false
  end

  def planned_dates
    dates = self.blogs.map do |blog|
      blog.planned_dates
    end
    dates.flatten!
  end

  def self.avatar_url email
    hash = Digest::MD5.hexdigest(email.strip)
    "http://www.gravatar.com/avatar/#{hash}?s=200&d=mm"
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @shane_url = User.avatar_url "shaneburkhart@gmail.com"
    @ryan_url = User.avatar_url "rzendacott@gmail.com"
  end
end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authenticate_user!

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = current_user.blogs

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @blogs }
    end
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.find(params[:id])

    # return unless authorize_blog

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/new
  # GET /blogs/new.json
  def new
    @blog = Blog.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @blog }
    end
  end

  # GET /blogs/1/edit
  def edit
    @blog = Blog.find(params[:id])

    return unless authorize_blog
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = current_user.blogs.build(params[:blog])

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render json: @blog, status: :created, location: @blog }
      else
        format.html { render action: "new" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /blogs/1
  # PUT /blogs/1.json
  def update
    @blog = Blog.find(params[:id])

    return unless authorize_blog

    respond_to do |format|
      if @blog.update_attributes(params[:blog])
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog = Blog.find(params[:id])

    return unless authorize_blog

    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url }
      format.json { head :no_content }
    end
  end

  private

    def authorize_blog
      if !current_user.my_blog? @blog
        redirect_to blogs_path, notice: "You don't have permission to do that!"
        return false
      end
      return true
    end

end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to blogs_path if current_user
  end
end

app/controllers/planned_dates_controller.rb
class PlannedDatesController < ApplicationController
  before_filter :authenticate_user!

  # GET /dates
  # GET /dates.json
  def index
    @dates = current_user.planned_dates

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dates }
    end
  end

  # GET /dates/1
  # GET /dates/1.json
  def show
    @date = PlannedDate.find(params[:id])

    return unless authorize_planned_date

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @date }
    end
  end

  # GET /dates/new
  # GET /dates/new.json
  def new
    @date = PlannedDate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @date }
    end
  end

  # GET /dates/1/edit
  def edit
    @date = PlannedDate.find(params[:id])
    return unless authorize_planned_date
  end

  # POST /dates
  # POST /dates.json
  def create
    @blog = Blog.find(params[:blog_id])
    @date = @blog.planned_dates.build(params[:date])
    @date.attributes = params[:planned_date]

    respond_to do |format|
      if @date.save
        format.html { redirect_to blog_path(params[:blog_id]), notice: 'PlannedDate was successfully created.' }
        format.json { render json: @date, status: :created, location: @date }
      else
        format.html { render action: "new" }
        format.json { render json: @date.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dates/1
  # PUT /dates/1.json
  def update
    @date = PlannedDate.find(params[:id])

    return unless authorize_planned_date

    respond_to do |format|
      if @date.update_attributes(params[:planned_date])
        format.html { redirect_to blog_path(@date.blog.id), notice: 'Date was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @date.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dates/1
  # DELETE /dates/1.json
  def destroy
    @date = PlannedDate.find(params[:id])

    return unless authorize_planned_date

    @date.destroy

    respond_to do |format|
      format.html { redirect_to blog_path(params[:blog_id])}
      format.json { head :no_content }
    end
  end

  private

    def authorize_planned_date
      if !current_user.my_planned_date? @date
        redirect_to blogs_path, notice: "You don't have permission to do that!"
        return false
      end
      return true
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/dates_helper.rb
module DatesHelper
end

app/helpers/faq_helper.rb
module FaqHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/index.html.haml
- content_for :title, "About Us"
.container
  .section
    .container
      %h1 About Us
      %hr
  .container
    .row
      .span12
        %p PlanSource was created to provide customers an efficient way to keep plans up to date.
        %p We understand plans can change daily.  Architects and engineers are continuously adding to and revising the drawings.  Reprinting every revision isn't cost effective, and can result in far too many sets of incorrect plans.  So the question is how can we reduce printing cost while while keeping the contractors up to date? The answer is mobile.
        %p The world is continuously moving towards the use of mobile devices, and storing data in the "cloud".  Having said that, mobile devices have yet to be used to store, and view sets of plans.  Yes, there are existing file sharing solutions, but none of them are tailored to the construction industry.  For instance, current solutions require you to have an internet connection to view their files.  However, this creates a problem when it comes to jobsites.  Most jobsites do not have wifi, so these solutions are useless.  PlanSource is different in that you only need internet to download the plans, but once they are downloaded you no longer need internet to view them.  This creates an ideal solution for jobsites that don't have wifi or internet.
        %p By utilizing mobile applications, and the cloud, PlanSource source aims to alleviate cost, and efficiently deliver plans to a jobsite.  We believe our construction tailored solution can help architects, engineers and contractors communicate more effectively.
    %hr
  .section
    .container
      %h2 The Team
      %hr
  .container
    .row
      .span3
        = image_tag @shane_url, class: "gravatar"
      .span9
        %h3 Shane Burkhart
        %p.lead.muted Co-Founder
        %p Hi, my name is Shane Burkhart and I am a computer engineeringcomputer science double major at the Missouri University of Science and Technology.  Most of my time is spent coding, working on computers, or looking for my next startup idea.  My goal is to use software and computers to solve as many real world problems as I can.
    %hr
  <!--
  .container
    .row
      .span9
        %h3 Ryan Endacott
        %p.lead.muted Co-Founder
        %p
      .span3
        = image_tag @ryan_url, class: "gravatar"
    %hr

  !-->

app/views/app/show.html.haml
%h1 App#index
%p Find me in app/views/app/index.html.haml

app/views/blogs/_form.html.haml
= simple_form_for(@blog, html: {:class => 'form-vertical' }) do |f|
  = f.error_notification
  = display_base_errors @blog
  = f.input :name, autofocus: true
  %br
  = f.button :submit, 'Add Blog', class: 'btn-primary'

app/views/blogs/edit.html.haml
.container
  %h1 Editing blog

  = render 'form'

  = link_to 'Back', blogs_path

app/views/blogs/index.html.haml
.container

  %h1 Your Blogs

  = link_to 'New Blog', new_blog_path

  %br
  %br

  %table.table
    %tr
      %th Name
      %th Controls
    - @blogs.each do |blog|
      %tr
        %td= blog.name
        %td
          %ul.nav.nav-pills
            %li= link_to 'Show', blog
            %li= link_to 'Edit', edit_blog_path(blog)
            %li= link_to 'Destroy', blog, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/blogs/new.html.haml
.container
  %h1 Add A Blog

  = render 'form'

  = link_to 'Back', blogs_path

app/views/blogs/show.html.haml
.container
  %h1= @blog.name
  %ul.nav.nav-pills
    %li= link_to 'Back', blogs_path
    %li= link_to 'Add a Plan', new_blog_planned_date_path(@blog)

  - @blog.planned_dates.each_slice(2).each do |date_slice|
    .row
      - date_slice.each do |date|
        .span6
          .box
            %h3= date.title
            %p= date.content
            %p.muted= date.date
            %ul.nav.nav-pills
              %li= link_to 'Edit', edit_blog_planned_date_path(date.blog.id, date)
              %li= link_to 'Destroy', blog_planned_date_path(date.blog.id, date), :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/faq/index.html.erb
<% content_for :title, "FAQ" %>
<div class="section">
  <div class="container">
    <h1>Frequently Asked Questions</h1>
    <hr>
  </div>
</div>
<div class="container">
  <p class="lead">What is PlanSource?</p>
  <p>PlanSource is a web and mobile application that allows users to upload plans that can later be viewed.</p>
  <hr>
  <p class="lead">Who should use PlanSource?</p>
  <p>PlanSource is primarily people in the construction industry such as engineers, architects, contractors, etc, but can be used by anyone.</p>
  <hr>
  <p class="lead">What is a Viewer account?</p>
  <p>A Viewer account lets you view jobs and plans that have been shared with you.  Viewers also have the ability to print and reshare if the owner of the job allows it.<p>
  <hr>
  <p class="lead">Who should use a Viewer account?</p>
  <p>A Viewer account should be used by someone that doesn't need to upload or create jobs.  Managers share their jobs with Viewers. Generally Viewers are contractors, or people that are not project managers.</p>
  <hr>
  <p class="lead">What is a Manager account?</p>
  <p>A Manager account has all of the abilities of a Viewer, plus they can create, edit, destroy, and share jobs and plans.  A Manager also has the ability to determine which plans can be printed.</p>
  <hr>
  <p class="lead">Who should use a Manager account?</p>
  <p>A Manager should be used by someone that needs to create jobs or upload plans.  Managers usually have many Viewers they share jobs with.  Generally these are project managers or architects.</p>
  <hr>
  <p class="lead">Does it cost to create an account?</p>
  <p>Right now, all accounts are free, but in the future, Manager accounts will have a subscription required.<p>
  <hr>
  <p class="lead">How many jobs can I create?</p>
  <p>The free trial for the Manager account lets you create two jobs without a subscription.  Once you have a subscription, there isn't a limit to how many jobs you can create.</p>
  <hr>
  <p class="lead">How many plans can I upload?</p>
  <p>Up to 100GB!<p>
  <hr>
  <p class="lead">Can I share my jobs?</p>
  <p>Yes, you just need the user's email you wish to share with.  If the user doesn't have an account, one will be created for them, and they will receive an email notifying them of the share.</p>
  <hr>
  <p class="lead">Can anyone reshare jobs I've shared with them?</p>
  <p>No, only users you allow can reshare your jobs.<p>
  <hr>
  <p class="lead">How do I view my plans?</p>
  <p>You can download the plans in the browser, or install one of the mobile applications on your device.<p>
  <hr>
  <p class="lead">Which mobile platforms are supported?</p>
  <p>Android and iPhone.</p>
  <hr>
  <p class="lead">Is the app free?</p>
  <p>The app is completely free.</p>
  <hr>
  <p class="lead">Can I print my plans?</p>
  <p>There are plans to implement printing, but as of right now printing is not available.</p>
  <hr>
</div>

app/views/faq/index.html.haml
%h1 Faq#index
%p Find me in app/views/faq/index.html.haml

app/views/home/index.html.haml
.container
  .marketing-section.small
    %h2.blue Dead Simple Content Scheduling
    %p.lead With just a few clicks, you can organize and schedule future content for your blog.  Multiple blogs?  No problem!  We handle that too.

  .marketing-section.small
    %h2.blue Planning Makes For Better Content
    %p.lead Planning out the content for your blog makes it easy to organize thoughts and ideas.  Your readers will thank you when your content keeps getting better and better.

  .marketing-section.small
    %h2.blue Email Notifications
    %p.lead We will send you an email reminding you to write the content you have scheduled.  A consistent blogging schedule will keep your readers engaged and happy.

app/views/layouts/_megaheader.html.haml
.banner-container.editable
  = image_tag "", class: "banner-loading-image"
  = image_tag "bridge.png", class: "banner-background-image"
  .banner-content
    .container
      %h1.banner-brand.text-center
        Blog Reminder
      .banner.text-center
        %h1 Plan For Better Content
        %p.lead Set a blog schedule to remind you to blog and improve your content.

      .marketing-section.row
        .offset4.span4
          = link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-large btn-block btn-success"


app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-static-top.navbar-inverse
  %nav.navbar-inner
    .container
      = link_to "Blog Reminder", root_path, class: "brand"
      %ul.nav.pull-right
        %li= link_to "About Us", about_path
        <!--%li= link_to "FAQ", faq_path !-->
        - if current_user
          %li= link_to "My Blogs", blogs_path
          %li= link_to "Edit Account", edit_user_registration_path
          %li= link_to "Logout", destroy_user_session_path, :method=>'delete'
        - else
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Login", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Simplebloglanding"
      %meta{:content => content_for?(:description) ? yield(:description) : "Simplebloglanding", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
    %body{data: { controller: controller_name, action: action_name}}
      = render "layouts/navigation"
      - if current_page? root_path
        = render "layouts/megaheader"
      .container
        = render "layouts/messages"
      = yield
      %footer

app/views/planned_dates/_form.html.haml
= simple_form_for(@date, url: ( @date.id ? blog_planned_date_path(params[:blog_id], @date.id) : blog_planned_dates_path(params[:blog_id])), html: {:class => 'form-vertical' }) do |f|
  = f.error_notification
  = display_base_errors @date
  = f.input :title, input_html: {class: "span9"}, autofocus: true
  = f.input :content, input_html: {rows: 10, cols: 100, class: "span9"}, autofocus: true
  = f.input :date, autofocus: true
  %br
  = f.button :submit, 'Add Date', class: 'btn-primary'

app/views/planned_dates/edit.html.haml
.container

  %h1 Editing date

  = render 'form'

app/views/planned_dates/index.html.haml
%h1 Listing dates

%table
  %tr
    %th
    %th
    %th

  - @dates.each do |date|
    %tr
      %td= link_to 'Show', date
      %td= link_to 'Edit', edit_date_path(date)
      %td= link_to 'Destroy', date, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Date', new_date_path

app/views/planned_dates/new.html.haml
.container
  %h1 New date

  = render 'form'

  = link_to 'Back', blog_path(params[:blog_id])

app/views/planned_dates/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_date_path(@date)
\|
= link_to 'Back', dates_path

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}